name: jira-timesheet
services:
  backend:
    build:
      context: ./jira-timesheet-api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./jira-timesheet-api/.env
    networks:
      - jira-network

  frontend:
    build:
      context: ./jira-timesheet-client
      dockerfile: Dockerfile
    ports:
      - "4234:4234"
    environment:
      - VITE_API_URL=/api
      - NGINX_PORT=4234
      - BACKEND_URL=http://backend:3000
    networks:
      - jira-network
    depends_on:
      - backend

networks:
  jira-network:
    driver: bridge 